import { NextRequest } from "next/server";
import { isRequestAuthenticated } from "@/lib/auth";
import { listMcpTools, executeMcpTool } from "@/lib/mcp-client";
import {
  mcpToolsToGeminiDeclarations,
  buildSystemInstruction,
  callGeminiTurn,
} from "@/lib/gemini";
import { SSEEvent, ToolExecutionRecord } from "@/lib/types";

export const maxDuration = 60; // Allow 60s runtime for multi-turn tool execution on Vercel

export async function POST(req: NextRequest) {
  if (!isRequestAuthenticated(req)) {
    return new Response(
      JSON.stringify({ error: "Unauthorized. Please authenticate with PIN." }),
      { status: 401, headers: { "Content-Type": "application/json" } }
    );
  }

  let body: any;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const userMessages = body.messages || [];
  if (!Array.isArray(userMessages) || userMessages.length === 0) {
    return new Response(JSON.stringify({ error: "Messages array required" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Create an SSE stream
  const encoder = new TextEncoder();
  const stream = new TransformStream();
  const writer = stream.writable.getWriter();

  const sendSSE = async (event: SSEEvent) => {
    try {
      const data = `data: ${JSON.stringify(event)}\n\n`;
      await writer.write(encoder.encode(data));
    } catch {
      // Client disconnected
    }
  };

  // Run agentic loop asynchronously in the background while streaming
  (async () => {
    try {
      // 1. Fetch available MCP tools
      const { tools } = await listMcpTools();
      const geminiTools = mcpToolsToGeminiDeclarations(tools);
      const systemInstruction = buildSystemInstruction(tools.map((t) => t.name));

      // 2. Format message history for Gemini API
      // Only keep text content and map assistant -> model
      const contents: any[] = [];
      for (const m of userMessages) {
        if (!m.content) continue;
        contents.push({
          role: m.role === "assistant" ? "model" : "user",
          parts: [{ text: m.content }],
        });
      }

      if (contents.length === 0) {
        await sendSSE({ type: "error", message: "No text content found in messages." });
        await writer.close();
        return;
      }

      const MAX_TURNS = 8;
      let finalContent = "";

      // 3. Autonomous Tool-Calling Agent Loop
      for (let turn = 0; turn < MAX_TURNS; turn++) {
        const responseData = await callGeminiTurn(
          contents,
          geminiTools,
          systemInstruction
        );

        if (responseData.error) {
          throw new Error(responseData.error.message || JSON.stringify(responseData.error));
        }

        const candidate = responseData.candidates?.[0];
        if (!candidate?.content) {
          throw new Error("No response content generated by Gemini.");
        }

        const parts = candidate.content.parts || [];
        const fnCalls = parts.filter((p: any) => p.functionCall);
        const textParts = parts.filter((p: any) => p.text && !p.thought);

        // A. If NO function calls: this is the final agent response
        if (fnCalls.length === 0) {
          const text = textParts.map((p: any) => p.text).join("") || "Done.";
          finalContent = text;

          // Stream the text smoothly in small chunks for responsive UX
          const chunkSize = 24;
          for (let i = 0; i < text.length; i += chunkSize) {
            const chunk = text.slice(i, i + chunkSize);
            await sendSSE({ type: "text_delta", content: chunk });
            // Micro delay to create natural reading stream
            await new Promise((r) => setTimeout(r, 15));
          }

          await sendSSE({ type: "done", fullContent: finalContent });
          await writer.close();
          return;
        }

        // B. Function calls detected: record model turn in conversation memory
        contents.push(candidate.content);

        // Stream any preliminary reasoning text from the model before tool execution
        if (textParts.length > 0) {
          const preText = textParts.map((p: any) => p.text).join("");
          if (preText.trim()) {
            await sendSSE({ type: "text_delta", content: preText + "\n\n" });
          }
        }

        const toolResponseParts: any[] = [];

        // Execute each requested tool call
        for (let i = 0; i < fnCalls.length; i++) {
          const call = fnCalls[i].functionCall;
          const fnName = call.name;
          const fnArgs = call.args || {};
          const callId = call.id || `call-${Date.now()}-${turn}-${i}`;
          const startTime = Date.now();

          const toolRecord: ToolExecutionRecord = {
            id: callId,
            name: fnName,
            arguments: fnArgs,
            status: "running",
            startedAt: startTime,
          };

          // Notify frontend that tool has started
          await sendSSE({ type: "tool_start", tool: toolRecord });

          let result: any = null;
          let executionError: string | undefined = undefined;

          try {
            result = await executeMcpTool(fnName, fnArgs);
          } catch (err: any) {
            executionError = err?.message || String(err);
            console.error(`[Tool Execution Error] ${fnName}:`, executionError);
          }

          const durationMs = Date.now() - startTime;

          // Notify frontend of tool result
          await sendSSE({
            type: "tool_result",
            id: callId,
            result,
            error: executionError,
            durationMs,
          });

          // Prepare functionResponse part for Gemini
          const responsePayload = executionError
            ? { error: executionError }
            : { result: result ?? { status: "success" } };

          const functionResponsePart: any = {
            functionResponse: {
              name: fnName,
              response: responsePayload,
            },
          };
          if (call.id) {
            functionResponsePart.functionResponse.id = call.id;
          }

          toolResponseParts.push(functionResponsePart);
        }

        // Feed tool results back into conversation history
        contents.push({
          role: "user",
          parts: toolResponseParts,
        });
      }

      // If maximum reasoning turns reached
      await sendSSE({
        type: "text_delta",
        content: "\n\n⚠️ *Reached maximum reasoning steps (8 turns). Operation completed.*",
      });
      await sendSSE({ type: "done" });
      await writer.close();
    } catch (err: any) {
      console.error("[Agent Chat Error]:", err);
      const isColdStart =
        err?.message?.includes("timed out") ||
        err?.message?.includes("fetch failed") ||
        err?.message?.includes("Render");

      await sendSSE({
        type: "error",
        message: err?.message || "An unexpected error occurred during execution.",
        isColdStart,
      });
      await writer.close();
    }
  })();

  return new Response(stream.readable, {
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}
